/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Eye(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/eye/eye.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.eye_low001.geometry}
        material={materials.Eye_material}
      />
    </group>
  );
}

useGLTF.preload("eye/eye.glb");
