/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tom Hodes (https://sketchfab.com/tomhodes)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/18915d2f17a2431fbefeb3eaf4411f16
title: Blue Eyeball (Free)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Eyeball(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/eyeball/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.blinn2}
      />
    </group>
  );
}

useGLTF.preload("/eyeball/scene.gltf");
