/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/knife.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.handle_high.geometry} material={nodes.handle_high.material} />
      <mesh
        geometry={nodes.handguard_high.geometry}
        material={nodes.handguard_high.material}
        position={[0, -0.31, -0.34]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.blade_low.geometry}
        material={nodes.blade_low.material}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.blade_high.geometry}
        material={nodes.blade_high.material}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.handle_low.geometry}
        material={nodes.handle_low.material}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.handguard_low.geometry}
        material={nodes.handguard_low.material}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
    </group>
  )
}

useGLTF.preload('/knife.glb')
