/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Mclaren.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.4, 0]}>
        <mesh geometry={nodes.Mesh089.geometry} material={materials.GreyBlack} />
        <mesh geometry={nodes.Mesh089_1.geometry} material={materials.Translucent} />
        <mesh geometry={nodes.Mesh089_2.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Mesh089_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Mesh089_4.geometry} material={materials.BodyPaint} />
        <mesh geometry={nodes.Mesh089_5.geometry} material={materials.OrangeBody} />
        <mesh geometry={nodes.Mesh089_6.geometry} material={materials.BlackMetallic} />
        <mesh geometry={nodes.Mesh089_7.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Mesh089_8.geometry} material={materials.Headlight} />
        <mesh geometry={nodes.Mesh089_9.geometry} material={materials.Top} />
        <mesh geometry={nodes.Mesh089_10.geometry} material={materials.BackLighs} />
        <mesh geometry={nodes.Mesh089_11.geometry} material={materials.Baclight} />
        <mesh geometry={nodes.Mesh089_12.geometry} material={materials.Shining} />
        <mesh geometry={nodes.Mesh089_13.geometry} material={materials['Back Plate']} />
        <mesh geometry={nodes.Mesh089_14.geometry} material={materials.Dashboard} />
        <mesh geometry={nodes.Mesh089_15.geometry} material={materials['Red Light']} />
        <mesh geometry={nodes.Mesh089_16.geometry} material={materials.Metallic} />
        <mesh geometry={nodes.Mesh089_17.geometry} material={materials['Seat lining']} />
        <mesh geometry={nodes.Mesh089_18.geometry} material={materials.Seat} />
        <mesh geometry={nodes.Mesh089_19.geometry} material={materials.screen} />
        <mesh geometry={nodes.Mesh089_20.geometry} material={materials.Crbon} />
        <mesh geometry={nodes.Mesh089_21.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Mesh089_22.geometry} material={materials.Material} />
        <group position={[1.2, -0.44, 1.66]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0}>
          <mesh
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5002.geometry}
            material={materials['wire_135006006.002']}
          />
          <mesh
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5002_1.geometry}
            material={materials['wire_162162162.002']}
          />
        </group>
        <group position={[-1.19, -0.44, 1.66]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
          <mesh geometry={nodes.uploads_files_637554_Wheel_ADV1_50.geometry} material={materials.wire_135006006} />
          <mesh geometry={nodes.uploads_files_637554_Wheel_ADV1_50_1.geometry} material={materials.wire_162162162} />
        </group>
        <group position={[1.23, -0.44, -2.14]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0}>
          <mesh
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5003.geometry}
            material={materials['wire_135006006.003']}
          />
          <mesh
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5003_1.geometry}
            material={materials['wire_162162162.003']}
          />
        </group>
        <group position={[-1.23, -0.44, -2.14]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
          <mesh
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5001.geometry}
            material={materials['wire_135006006.001']}
          />
          <mesh
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5001_1.geometry}
            material={materials['wire_162162162.001']}
          />
        </group>
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0, 4.96, 0]} />
    </group>
  )
}

useGLTF.preload('/Mclaren.glb')
