/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tom Hodes (https://sketchfab.com/tomhodes)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/18915d2f17a2431fbefeb3eaf4411f16
title: Blue Eyeball (Free)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Eyeball(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.blinn2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
